### ISSUE TITLE
Legendas.tv e addon Pulsar não funciona!

### ISSUE THREAD

**Issue by samukets** [gfjardim/service.subtitles.legendastv#12]
Olá amigo, o plugin de legendas (legendas.tv) não funciona com o addon pulsar, antigamente funcionava. Hoje em dia sempre que tento achar legenda para alguma série ele não acha mesmo constando no site, até mesmo se eu tentar a busca manual ele não acha, o que pode ser feito?

**Comment by gfjardim** [comment]
Vou verificar e lhe dou retorno.
Em 11/11/2015 03:31, "samukets" <notifications@github.com> escreveu:

**Comment by samukets** [comment]
Obrigado amigo pela ajuda, se precisar posso gravar um vídeo demonstrando o problema.

Aguardo retorno...

**Comment by DevulskyA** [comment]
Parou de funcionar há aproximadamente 1 mês.

**Comment by gfjardim** [comment]
Algum status sobre esse problema? Ainda ocorre no 2.3.2?

**Comment by DevulskyA** [comment]
Está ok agora! 
Obrigado gjjardim! Seu addon é extremamente útil.
