### ISSUE TITLE
nao da legenda certa com quasar

### ISSUE THREAD

**Issue by deusbraga** [gfjardim/service.subtitles.legendastv#13]
Oi e muito obrigado pelo addon. Ultimamente me dá sempre legenda errada, acontece com SALTS as vezes e sempre com Quasar. Podia dizer se tem solução?

Mais uma vez obrigado

**Comment by gfjardim** [comment]
Não uso esses addons e não dou suporte a eles. Se por acaso descobrir a solução, eu posso tentar consertar.

**Comment by deusbraga** [comment]
Eu creio que o problema é que deve algures entre o addon de video e o
legendas tv  algo deve estar usando o nome traduzido para procurar legenda,
no de vídeo já experimentei forçar usar o nome original mas o legendas.tv
não tem essa opção. Mandar-lhe o log ajudaria?


Muito obrigado por responder.


Domingos Teixeira

2016-03-01 10:34 GMT+00:00 gfjardim <notifications@github.com>:

> Não uso esses addons e não dou suporte a eles. Se por acaso descobrir a
> solução, eu posso tentar consertar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gfjardim/service.subtitles.legendastv/issues/13#issuecomment-190654825>
> .
>



-- 
Great men are forged in fire. It is the privilege of lesser men to light
the flame. Whatever the cost. Warrior Doctor
