### ISSUE TITLE
Busca traz legenda de outro filme/Serie

### ISSUE THREAD

**Issue by onemustfall** [gfjardim/service.subtitles.legendastv#15]
Quando tento baixar as legendas para o seriado OUTCAST, 2016 o plugin traz como resultado outra séria de nome similar ( outcasts ). Quando entro no site consigo filtar a série correta, mas pelo AddOn apenas aparece a segunda opção.

http://legendas.tv/busca/Outcast/40943 
http://legendas.tv/busca/Outcasts/23471

No mais, o ADDon funciona sem problemas.  Já deixo aqui meus agradecimentos pela atenção e pelo excelente trabalho com este addon.

**Comment by riotbr** [comment]
Tive este problema e resolvi renomeando a pasta da série com o que aparece exatamente no TVDB.

**Comment by onemustfall** [comment]
Riotbr, 

O que relatei acontecia independentemente do nome da pasta. No caso eu estava assistindo por streaming e mesmo digitando manualmente o nome, ele escolhia o segundo "outcasts", talves devido ao id ( 23471 ) ser menor.

**Comment by onemustfall** [comment]
Com a versão nova, a situação reportada não ocorre mais.

**Comment by gfjardim** [comment]
Foi por causa desse problema que eu inclui um filtro por IMDB id. Acredito que a filtragem tenha ficado mais acurada.

Obrigado por indicar o problema.

**Comment by onemustfall** [comment]
Obrigado pelo seu tempo e por ajustar o ADDon pra gente! :)
