### ISSUE TITLE
Erro com packs

### ISSUE THREAD

**Issue by riotbr** [gfjardim/service.subtitles.legendastv#16]
Olá.

Quando a legenda encontrada é uma apenas, o download ocorre sem problemas, assim como a descompactação do arquivos.

Se for um pack, ou se houver mais de uma versão para o mesmo episódio/filme, ocorrem erros: informa que não foi possível o download, mas isso parece um erro genérico pois não ocorrem erros como no caso citado anteriormente.

Se houver como auxiliar com algum log ou algo assim, por favor, me informem como fazê-lo.

- Openelec 5.0.8 32 bits (não tenho a opção de utilizar a versão 64 bits);
- Kodi v14;
- Versão do add-on: a mais recente.

**Comment by onemustfall** [comment]
Estava com o mesmo erro. A versão ( 2.3.1...)  mais recente funciona
==> http://www.xbmcbrasil.net/thread-1911.html

**Comment by riotbr** [comment]
Baixei o arquivo e, após a instalação, ainda consta como 2.3.0. Só não testei com os packs ainda; o farei agora mesmo.

**Comment by onemustfall** [comment]
Está como 2.3.0 pois o "addon.xml" não foi editado. Mas este arquivos contém a versão 2.3.1 disponibilizada aqui.

**Comment by gfjardim** [comment]
Valeu pessoal por me indicar o erro de versão. Já enviei uma nova versão com a correção.
